export const GET_ANIMAL_ID_REQUESTED="GET_ANIMAL_ID_REQUESTED"
export const GET_ANIMAL_ID_SUCCESS="GET_ANIMAL_ID_SUCCESS"
export const GET_ANIMAL_ID_FAILED="GET_ANIMAL_ID_FAILED"

export const UPDATE_ANIMAL_ID_REQUESTED="UPDATE_ANIMAL_ID_REQUESTED"
export const UPDATE_ANIMAL_ID_SUCCESS="UPDATE_ANIMAL_ID_SUCCESS"
export const UPDATE_ANIMAL_ID_FAILED="UPDATE_ANIMAL_ID_FAILED"

export const DELETE_ANIMAL_ID_REQUESTED="DELETE_ANIMAL_ID_REQUESTED"
export const DELETE_ANIMAL_ID_SUCCESS="DELETE_ANIMAL_ID_SUCCESS"
export const DELETE_ANIMAL_ID_FAILED="DELETE_ANIMAL_ID_FAILED"

export const SAVE_ANIMAL_REQUESTED="SAVE_ANIMAL_REQUESTED"
export const SAVE_ANIMAL_SUCCESS="SAVE_ANIMAL_SUCCESS"
export const SAVE_ANIMAL_FAILED="SAVE_ANIMAL_FAILED"

export const GET_ANIMALS_REQUESTED = "GET_ANIMALS_REQUESTED "
export const GET_ANIMALS_SUCCESS = "GET_ANIMALS_SUCCESS "
export const GET_ANIMALS_FAILED = "GET_ANIMALS_FAILED "
